export const MAX_CHARS = 5;
export const MAX_BOARD = 6;
export const MAX_EMPTY_ROWS = MAX_BOARD - 1;
export const EVAL_MS = 350;
export const GAME_OVER_MS = 100;
export const WIN_MS = 200;
export const EVAL_DELAY = 350 * 5;
export const REFRESH_DELAY = 2200;
export const GAME_WON_DELAY = EVAL_DELAY + WIN_MS * 8;
